version: '3.8'

services:
  db:
    container_name: postgre_db
    image: postgres
    env_file:
      - .env

  app:
    container_name: insurance_api
    build: .
    command:  bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --reload --log-level error --host 0.0.0.0 --port 8000'
    ports:
      - "8008:8000"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
